# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[battery]
full_symbol = 'ðŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ðŸ’€ '

[[battery.display]]
threshold = 15
style = 'bold red'

[character]
#success_symbol = '[->](bold green)'
#error_symbol = '->](bold red)'
success_symbol = '[|>](bold green)'
error_symbol = '[|>](bold red)'
#success_symbol = '[âžœ](bold green)'
#error_symbol = '[âžœ](bold red)'

[container]
#format = '[$symbol \[$name\]]($style) '
format = '[$symbol \[$name\]](blue) '
#format = '[$symbol]($style) '

#[directory]
#use_logical_path = false

#[directory.substitutions]
#"/var/home/jose" = "~"

[kubernetes]
#format = '[$symbol$context( \($namespace\))]($style) in ' # default
format = '[$symbol$namespace]($style) in ' # default
disabled = false

#[line_break]
#disabled = true

[ocaml]
disabled = false
